[config]
default_to_workspace = false

[tasks.build-portald]
command = "cargo"
args = ["build" , "-p", "portald"]

[tasks.run-portald]
dependencies = ["build-portald"]
command = "sudo"
args = ["./target/debug/portald", "run", "--config", "config.local.toml"]

[tasks.install-portald]
dependencies = ["build-portald"]
command = "cargo"
args = ["install", "--path", "bins/portald"]

[tasks.build-pgun]
command = "cargo"
args = ["build" , "-p", "portal-client"]

[tasks.build-pgun-release]
command = "cargo"
args = ["build" , "-p", "portal-client", "--release"]

[tasks.install-pgun]
command = "cargo"
args = ["install", "--path", "bins/pgun"]

