[config]
default_to_workspace = false

[tasks.build-portald]
command = "cargo"
args = ["build" , "-p", "portal-server"]

[tasks.run-portald]
dependencies = ["build-portald"]
command = "sudo"
args = ["./target/debug/portald", "--config", "config.local.toml"]

[tasks.build-pgun]
command = "cargo"
args = ["build" , "-p", "portal-client"]

[tasks.build-pgun-release]
command = "cargo"
args = ["build" , "-p", "portal-client", "--release"]

[tasks.install-pgun]
command = "cargo"
args = ["install", "--path", "bins/portal-client"]

