pub const ZONE_CONTROL_ENTRY_INCLUDE: &str = "$INCLUDE";
pub const ZONE_CONTROL_ENTRY_INCLUDE_LEN: usize = ZONE_CONTROL_ENTRY_INCLUDE.len();

pub const ZONE_CONTROL_ENTRY_ORIGIN: &str = "$ORIGIN";
pub const ZONE_CONTROL_ENTRY_ORIGIN_LEN: usize = ZONE_CONTROL_ENTRY_ORIGIN.len();
