[package]
name = "portal-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "portald"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
portal = { path = "../../" }
anyhow = "1.0.66"
